User fix
UCF/unify-events pull request #45
Opened 2020-09-22 14:25 UTC by jmbarne3

Enhancements:
* Updated the User and Permissions view to use a select2 field instead of traditional select.

2020-09-22 16:46 UTC, rjucf approved these changes

2020-09-23 13:32 UTC, jmbarne3 commented
Resolves #44

2020-09-23 13:49 UTC, cadie approved these changes

2020-09-23 13:49 UTC, cjg89 requested changes

2020-09-23 13:49 UTC, cjg89 commented on settings.py
> +            'level': 'DEBUG'
Are these log level changes intentional?  Also, would it make more sense to move logging settings to settings_local.py to make it easier to adjust logging settings for local debugging?

2020-09-23 13:49 UTC, cjg89 commented on events/views/manager/search.py
> +                    'text': "{0} {1} - {2}".format(user.first_name, user.last_name, user.username)
While it's unlikely, it's possible for user first/last names to be empty.  We may want to check for that here before displaying empty strings.

2020-09-23 13:49 UTC, cjg89 commented on templates/events/manager/calendar/update/update-users.html
> +  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
For consistency with the other third-party plugins we include styles for in the admin, I think it would make more sense to import this css in [style-backend.scss](https://github.com/UCF/unify-events/blob/pre-v2.0.0/static_files/assets/scss/style-backend.scss).

2020-09-23 13:49 UTC, cjg89 commented on templates/events/manager/calendar/update/update-users.html
> +    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
Same thing as the note about the stylesheet above--I think it'd make more sense to require this in [script-manager.js](https://github.com/UCF/unify-events/blob/pre-v2.0.0/static_files/assets/js/script-manager.js)

2020-09-23 13:53 UTC, jmbarne3 commented on settings.py
> +            'level': 'DEBUG'
The change was not intentionally kept, it was just there while I was trying to debug an issue in dev. The logging is all kinds of messed up on this project now. We probably need to devote another PR to fixing it.

2020-09-23 14:14 UTC, jmbarne3 commented on events/views/manager/search.py
> +                    'text': "{0} {1} - {2}".format(user.first_name, user.last_name, user.username)
Fixed

2020-09-23 14:41 UTC, cjg89 approved these changes

2020-09-23 14:44 UTC, merged